<?php $__env->startSection('terms_of_use'); ?>
<!--Content Area Begin-->
<section class="row pageCover">
    <div class="container">
        <div class="row m0">
            <div class="fleft page_name">Terms Of Use</div>
            <div class="fright page_dir">
                <ul class="list-inline">
                    <li><a href="index-2.html">home</a></li>
                    <li>Terms Of Use</li>
                </ul>
            </div>
        </div>
    </div>
</section>

<section class="row contentRow blogWsidebar">
    <div class="container">
        <div class="row">
            <div class="col-sm-10 blogCol">
                <div class="row m0 single_blog">
                    <div class="post_desc">
                      <h4 class="blogTitle">Terms Of Use</h4>
                      <h4>1) GENERAL</h4>
                      <ul class="list-unstyled"> 
                        <ol type="a">
                        <li>
                        <p>
                        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                        </p>
                        </li>
                        <li>
                        <p>
                        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.mozitoo.com The domain name www.mozitoo.com ("Website"), including its online services, such as use of software on Website to offer leasing and property management services for residential properties and also, provides rental property supervision and management, from rent collection, tenant relations, move in, move out assistance , bill payments and property maintenance, etc. Information, text, graphics, images and information obtained from service providers, any other website linked to this website, and any other material contained on the Website ("Materials") provided by Website is owned and operated by TEENEX INNOVATIONS PVT. LTD (“Company”) incorporated under the provisions of the Companies Act, 2013, and having its registered office at, LGF-5, Bajrang Plaza, Sector 8, Vikas Nagar Lucknow 226066, where such expression shall, unless repugnant to the context thereof, be deemed to include its respective representatives, administrators, employees, directors, officers, agents and their successors and assigns.
                        </p>
                        </li>
                        <li>
                        <p>
                        For the purpose of these Terms of Use (“Terms”), wherever the context so requires:
                        </p>
                        </li>
                    <ul class="list-unstyled">                    
                            <ol type="I">
                                <li>
                                    <p>
                                    The term ‘You’ &‘User’ shall mean any legal person or entity accessing or using the services provided on this Website, who is competent to enter into binding contracts, as per the provisions of the Indian Contract Act, 1872;
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    The terms ‘We’, ‘Us’ & ‘Our’ shall mean the Website and/or the Company, as the context so requires.
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    The terms ‘Party’ & ‘Parties’ shall respectively be used to refer to the User and the Company individually and collectively, as the context so requires.
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    “Effective date” means the date of release of this agreement.
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    “Agreement” is defined as the agreement between the user/Property Owner / Tenant / Property Advisor and the Company governed by the Terms and Conditions of service.
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    “Property Owner” means the individual or company or entity who listed his/her property on the website for property management, rent etc.
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    “Tenant” means the individual or company or entity, leases the property or takes property on rent which is listed on the website with reference to company or property advisors.
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    “Property Advisor” means any company or individual utilizing company’s platform to offer services to customers or clients.
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    “Commission” means amount payable to Property Advisor in lieu of service contract.
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    “Order” means a request confirmed by the User for the Services.
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    “Services” means online services provided or performed by the Company for the User through its Website.
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    “Indemnified party” means TEENEX INNOVATIONS PVT. LTD. and its subsidiaries, affiliates, officers, agents, employees, members, representative and agents.
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    “Confidential Information” means information (in any form) which is confidential either to User or to the Company and which either User discloses to the Company or the Company disclose to the User in connection with the Services.
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    Users include both the Subscriber/Advertiser(s) and Browser/Visitor(s).
                                    </p>
                                </li>
                                <li>
                                    <p>
                                    Service' or 'Services' would mean to include the interactive online information Service offered by the company on the internet through which the user may access information carried by company in the database maintained by it. The terms would include to mean the search tools through which the User can search through the hosted databases and information using a number of search tools that are present with a selection matching their search criteria. Users then select one or more of the items presented to view the full document/ record. The term Service does not extend to company acting as an agent either express or implied on behalf of any User/Customer and is merely acting as a medium of information exchange/faciliator.
                                    </p>
                                </li>
                            </ol>                 
                        </ul>
                        <li>
                            <p>
                            The headings of each section in these Terms are only for the purpose of organizing the various provisions under these Terms in an orderly manner, and shall not be used by either Party to interpret the provisions contained herein in any manner. Further, it is specifically agreed to by the Parties that the headings shall have no legal or contractual value.
                            </p>
                        </li>
                        <li>
                            <p>
                            The use of the Website by the User is solely governed by these Terms as well as the Privacy Policy (“Policy”), available on Website and any modifications or amendments made thereto by the Company from time to time, at its sole discretion. Visiting the home page of the Website and/or using any of the services provided on the Website shall be deemed to signify the User’s unequivocal acceptance of these Terms and the aforementioned Policy, and the User expressly agrees to be bound by the same. The User expressly agrees and acknowledges that the Terms and Policy are co-terminus, and that expiry / termination of either one will lead to the termination of the other, save as provided in Section 4 hereunder.
                            </p>
                        </li>
                        <li>
                            <p>
                            The User unequivocally agrees that these Terms and the aforementioned Policy constitute a legally binding agreement between the User and the Company, and that the User shall be subject to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided by the Website, and that the same shall be deemed to be incorporated into these Terms, and shall be treated as part and parcel of the same. The User acknowledges and agrees that no signature or express act is required to make these Terms and the Policy binding on the User, and that the User’s act of visiting the any part of the Website constitutes the User’s full and final acceptance of these Terms and the aforementioned Policy. If you do not agree with any of these terms and conditions then you should not access or use the website/app.
                            </p>
                        </li>
                        <li>
                            <p>
                            The Company reserves the sole and exclusive right to amend or modify these Terms without any prior permission or intimation to the User, and the User expressly agrees that any such amendments or modifications shall come into effect immediately. The User has a duty to periodically check the terms and stay updated on its requirements. If the User continues to use the Website following such a change, the User will be deemed to have consented to any and all amendments / modifications made to the Terms. In so far as the User complies with these Terms, he/she is granted a personal, non-exclusive, non-transferable, revocable, limited privilege to enter and use the Website.
                            </p>
                        </li>
                        <li>
                            <p>
                            These terms and conditions also apply on all registered Users as well as unregistered Users in respect of all new services or features introduced on website in future as well.
                            </p>
                        </li>
                        <li>
                            <p>
                            The user name and password are either allotted by company or chosen by the Subscriber or agreed upon by the company. It is made abundantly clear that only the authorized User has the right to access the Services so offered by the company.
                            </p>
                        </li>
                        <li>
                            <p>
                            The Company, reserves its right to withdraw wholly or in partly, without assigning any reason, any of website services or properties with or without any notice.
                            </p>
                        </li>
                        </ol>
                        </ul>
                        <h4>2) OUR SERVICES</h4>
                        <ul class="list-unstyled"> 
                        <ol>
                            <p>       
                            The Company is technical facilitator that aims to provide a platform for accessing services and information related to real estate. It offers an array of online services relating to real estate/property including listing and search of properties on the website for leasing and property management services for residential properties through its portal www.mozitoo.com. The Company provides full-service property Management Company, providing rental property supervision and management, from rent collection, tenant relations, tenant move in/move out assistance, bill payments and property maintenance, etc. Our management concept is founded on professionalism, integrity, accountability, and quality service that guarantee the maximum return from your investment, while maintaining your property at the highest standards to attract the best tenants possible and finding best property for tenants as per their requirements. The Services may sometimes be located on third-party websites or applications, either as links from an add-on service to, or otherwise in connection with, websites or applications that those third parties control. The Company disclaims any warranties express or implied connected with use of the Website including its quality, availability or accuracy, which are provided on an "AS IS" basis.
                            </p>
                        </ol>
                        </ul>
                        <h4>3) PURPOSE OF TEENEX INNOVATIONS PVT. LTD.’S PLATFORM</h4>
                        <ul class="list-unstyled"> 
                        <ol>
                            <p>       
                            The company provides platform to Property Owner / Tenant / Property Advisor. It acts merely as a service provider to Property Owner and Tenants. The company provides complete end to end property management services to Property Owner from sourcing tenants, maintaining and managing the property. The company provides property search services to tenants and enable them in finding best property suited to their requirement and manage tenant issues. Property Advisors are the Company’s partners who refer prospect property owners and tenant leads in return for referral fees.
                            <br/><br/>
                            Mozitoo.com currently provides a platform for all rental property owners, landlords (collectively referred to as "Participating Affiliates") and their respective tenants, remitting payments for availing rent payment and other property management services. Mozitoo.com facilitates various electronic payment options for the use of services by the users for their monthly rents, periodic rents, security deposits, other deposits, and all other fees and charges related to leased space, fixed or variable (the “Service”).Split your rent feature provides the tenant to share rent, security deposit or any other expenses with their flatmates. You, as the tenant of a Participating Landlord, are eligible to use the Services of the website to pay your rent and any related fees. Your credit card, or other on-line electronic payments made through the Service will be remitted to your Participating Landlord in accordance to the information provided by you. You will receive a timely confirmation/notification from Mozitoo.com acknowledging the Mozitoo.com receipt of credit card or on-line electronic payments. Unless explicitly stated otherwise, any new features, which enhance or augment Mozitoo.com’s current service offering shall be subject to the terms and conditions of service. You must obtain access to the World Wide Web and/or Internet in order to use the Service, either directly or through other devices that access web-based content. You must also pay any service fees associated with such access. In addition, you must supply all necessary equipment to connect to the World Wide Web and/or Internet, including a computer, a modem or other access devices.
                            </p>
                        </ol>
                        </ul>    
                        <h4>4) SERVICE CONTRACT</h4>   
                        <ul class="list-unstyled"> 
                        <ol>
                            <p>       
                            The Users expressly acknowledges, agrees and understand that:
                            </p>
                        <ol type="a">
                            <li>
                                <p>       
                                The Company is merely a platform where users may act as a Property Owner or Tenant or Property Advisor etc.
                                </p>
                            </li>
                            <li>
                                <p>
                                User acknowledges that she/he is not an employee of the company and further they are not directed or supervised or controlled by the company.
                                </p>
                            </li>
                            <li>
                                <p>
                                Company shall not hold any liability arises from service contract or any act or omissions of users.
                                </p>
                            </li>
                            <li>
                                <p>
                                The Company makes no representation as to the reliability, capability or qualifications of any property advisor or tenant or property owner or the quality, security or legality of any services.
                                </p>
                            </li>
                            <li>
                                <p>
                                The Company does not ensure the accuracy of, endorse or recommend any content and the User uses such Content at the his/her own risk. A User may access the listings/advertisements in the Service solely to obtain initial information from which further evaluation and investigation may commence.
                                </p>
                            </li>
                            <li>
                                <p>
                                User shall limit access to and use of listings, deals to personal and internal use, and shall not use listings obtained from the Service for further distribution, publication, public display, or preparation of derivative works or facilitate any of these activities in any way.
                                </p>
                            </li>
                            <li>
                                <p>
                                User shall not use or reproduce any Content that is obtained from the Service, or that is otherwise made available to User in the Service, for or in connection with any other listing/advertising Service or device.
                                </p>
                            </li>
                            <li>
                                <p>
                                User further shall not use the Service provided by the company in any other manner for or in connection with any other listing Service or device.
                                </p>
                            </li>
                            <li>
                                <p>
                                Users violating these specific terms, specifically those Users searching the Service in an abusive or excessive manner, by automated or manual means, shall be subject to immediate termination of their membership without notice.
                                </p>
                            </li>
                        </ol>
                        </ol>
                        </ul>
                        <h4>5) ELIGIBILITY</h4>   
                        <ul class="list-unstyled"> 
                        <ol>
                            <p>
                            The User represents and warrants that he/she is competent and eligible to enter into legally binding agreements and that he/she has the requisite authority to bind himself/herself to these Terms, as determined solely by the provisions of the Indian Contract Act, 1872. The User may not use this Website if he/she is not competent to contract under the Indian Contract Act, 1872, or is disqualified from doing so by any other applicable law, rule or regulation currently in force.
                            </p>
                        </ol>
                        </ul>
                        <h4>6) TERM</h4>   
                        <ul class="list-unstyled"> 
                        <ol>
                            <p>
                                These Terms shall continue to form a valid and binding contract between the Parties, and shall continue to be in full force and effect until:
                            </p>
                            <ol type="a">
                            <li>
                                <p>       
                                The User continues to access and use the Website; or
                                </p>
                            </li>
                            <li>
                                <p>
                                The Transaction between the Parties, if any, concludes to the satisfaction of both Parties;
                                </p>
                            </li>
                            </ol>
                            <p>
                            Whichever is longer. The Parties agree that certain portions of these Terms (“Sections”), such as Sections 11, 13, 14, 15 & 16, shall continue to remain in full force and effect indefinitely, even after the expiry or termination of these Terms as contemplated herein.
                            </p>
                        </ol>
                        </ul>
                        <h4>7) TERMINATION</h4>   
                        <ul class="list-unstyled"> 
                        <ol>
                            <ol type="a">
                            <li>
                                <p>       
                                The Company reserves the right, in its sole discretion, to remove user / Property Owner / Property Advisor / Tenant to access the website and also has a right to terminate the access of the services offered on the Website/App, or any portion thereof, at any time, without notice or cause
                                </p>
                            </li>
                            <li>
                                <p>
                                User / Property Owner / Property Advisor / Tenant may make a request of termination but they are not entitled to any refund of payment.
                                </p>
                            </li>
                            <li>
                                <p>
                                The User shall continue to be bound by these Terms, and it is expressly agreed to by the Parties that the User shall not have the right to terminate these Terms till the expiry of the same, as described in Section 4 herein above.
                                </p>
                            </li>
                            </ol>
                        </ol>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!--Content Area End-->

<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.master1', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>